spring:
  application:
    name: springboot-jeecgboot
  datasource:
    url: jdbc:mysql://localhost:3306/a_springboot_jeecgboot
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver